//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hust.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao
    {
        public int IdBaoCao { get; set; }
        public Nullable<int> IdCongTac { get; set; }
        public Nullable<int> IdNguoiLapBaoCao { get; set; }
    }
}
