//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hust.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiPhi()
        {
            this.ChiPhiCongTacs = new HashSet<ChiPhiCongTac>();
        }
    
        public int IdChiPhi { get; set; }
        public string TenChiPhi { get; set; }
        public string TienChi { get; set; }
        public Nullable<int> IdChucVuSuDung { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThaiChiPhi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiCongTac> ChiPhiCongTacs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual TrangThaiHeThong TrangThaiHeThong { get; set; }
    }
}
