//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hust.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhiCongTac
    {
        public int Id { get; set; }
        public Nullable<int> IdCongTac { get; set; }
        public Nullable<int> IdNhanVien { get; set; }
        public Nullable<int> IdChiPhi { get; set; }
        public Nullable<int> TrangThaiChiPhiCongTac { get; set; }
    
        public virtual ChiPhi ChiPhi { get; set; }
        public virtual CongTac CongTac { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TrangThaiHeThong TrangThaiHeThong { get; set; }
    }
}
