//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hust.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucNangHeThong
    {
        public int IdChucNangHeThong { get; set; }
        public string TenChucNang { get; set; }
        public Nullable<int> IdChucVu { get; set; }
        public Nullable<int> IdParent { get; set; }
        public Nullable<int> IdChild { get; set; }
        public string Slug { get; set; }
        public string FaIcon { get; set; }
        public Nullable<int> TrangThaiChucNang { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual TrangThaiHeThong TrangThaiHeThong { get; set; }
    }
}
