//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hust.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongTac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CongTac()
        {
            this.ChiPhiCongTacs = new HashSet<ChiPhiCongTac>();
        }
    
        public int IdCongTac { get; set; }
        public string TenCongTac { get; set; }
        public Nullable<int> IdNguoiLapKeHoach { get; set; }
        public Nullable<int> IdPhongBan { get; set; }
        public string DiaDiemCongTac { get; set; }
        public Nullable<System.DateTime> NgayDiCongTac { get; set; }
        public string NoiDungCongTac { get; set; }
        public string TongChiPhiCongTac { get; set; }
        public Nullable<int> TrangThaiCongTac { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiCongTac> ChiPhiCongTacs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TrangThaiHeThong TrangThaiHeThong { get; set; }
    }
}
