//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hust.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChiPhiCongTacs = new HashSet<ChiPhiCongTac>();
            this.CongTacs = new HashSet<CongTac>();
        }
    
        public int IdNhanVien { get; set; }
        public string HoTenNhanVien { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string IpDangNhapGanNhat { get; set; }
        public Nullable<int> IdPhongBan { get; set; }
        public Nullable<int> IdChucVu { get; set; }
        public Nullable<System.DateTime> NgayDangNhapGanNhat { get; set; }
        public string Token { get; set; }
        public Nullable<int> TrangThaiNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiCongTac> ChiPhiCongTacs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongTac> CongTacs { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TrangThaiHeThong TrangThaiHeThong { get; set; }
    }
}
